### ISSUE TITLE
Error while creating the paste. Not a valid paste bin url!

### ISSUE THREAD

**Issue by kuai6** [kennedyoliveira/ultimate-pastebin-intellij-plugin#19] opened 2017-07-15 08:08 UTC
Unable to create paste's.

11:03	Ultimate PasteBin
			Error while creating the paste.
			Not a valid paste bin url!

**Comment by rwagner00** [comment] 2017-08-15 13:26
I'm having the same error with the same message (other than the timestamp, obviously). 

System details: Ubuntu 16.04 LTS, PhpStorm 2017.2

**Comment by kennedyoliveira** [comment] 2017-08-17 01:04
Thanks for the report, and sorry for the long time to delay, i'll check whats happening.

**Comment by Thibstars** [comment] 2017-10-16 09:32
Just a quote from pastebin's site:

"IMPORTANT: Please update all API calls to HTTPS before August 1st. We will then block all API calls over HTTP."

I'm sharing this in case you are still using HTTP.

**Comment by danemorgan** [comment] 2017-11-29 14:23
I am getting this error as well, on my first attempt to save a paste.

**Comment by Psaproxy** [comment] 2018-01-12 08:16
I confirm [error](https://dropfile.to/rMRXMzo). @kennedyoliveira is it possible to fix it?

**Comment by danemorgan** [comment] 2018-01-12 14:28
I dug through the repository and found where there is a call made to Pastebin with a hard http:// protocol I suspect that is the problem, but I'm a PHP/WordPress guy. I'm not sure how to make that change in this and test it in PHPStorm.

**Comment by danemorgan** [comment] 2018-01-12 14:30
I think the problem is line 77 in https://github.com/kennedyoliveira/ultimate-pastebin-intellij-plugin/blob/724a5565113ef6fc95bcc7cc447eec89e53af262/src/com/github/kennedyoliveira/ultimatepastebin/settings/PasteBinConfigurationForm.java

But I'm a PHP/Wordpress guy I don't know how to turn that suspicion into a test on PHPStorm.

**Comment by rwagner00** [comment] 2018-01-12 14:45
@danemorgan - I'm inclined to think you're right, Pastebin has been blocking insecure requests like this one for a little while. Like yourself (mostly) I'm a PHP/Drupal guy and have no idea how to repackage this in an installable format.

**Comment by kennedyoliveira** [comment] 2018-01-12 23:30
Hey everyone! First of all, apologies for the delay, i'm not having time to work on this project, but i'll try to fix it this weekend. This happens all the time or is random?

**Comment by rwagner00** [comment] 2018-01-12 23:32
The error happens 100% of the time.

**Comment by danemorgan** [comment] 2018-01-13 14:55
It has happened to me from the first time I installed. I have not been able to save a paste yet.

**Comment by kennedyoliveira** [comment] 2018-01-13 16:14
Thanks for the feedback, i found the problem, the plugin depends on another API that i created, and i did a update on this library for communicating with Pastebin and did not update the plugin with the new version, so the calls was going through HTTP, i'll release a new version and it should be available soon, now Jetbrains has a approval process of plugins version so it won't be available imediatly

**Comment by kennedyoliveira** [comment] 2018-01-20 00:32
@danemorgan could you check the new version and see if it fixes the problem to you?

**Comment by danemorgan** [comment] 2018-01-24 06:14
@kennedyoliveira I confirm that your fix works for me. I am able to send pates now.

**Comment by kennedyoliveira** [comment] 2018-01-24 10:51
@danemorgan great! I'm closing the issue, if you found anything else, please open and issue and I'll work on it :)

**Closed by kennedyoliveira** 2018-01-24 10:51 UTC
